<?php
$artists = [

    ['name' => 'ユニコーン', 'aliases' => ['Unicorn', 'UNICORN']],
    ['name' => 'サザンオールスターズ', 'aliases' => ['Southern All Stars', 'SAS']],
    ['name' => 'スピッツ', 'aliases' => ['Spitz']],
    ['name' => 'Mr.Children', 'aliases' => ['ミスチル', 'ミスターチルドレン']],
    ['name' => 'BUMP OF CHICKEN', 'aliases' => ['バンプ']],
    ['name' => 'RADWIMPS', 'aliases' => ['ラッド']],
    ['name' => 'ONE OK ROCK', 'aliases' => ['ワンオクロック', 'ワンオク']],
    ['name' => 'GLAY', 'aliases' => []],
    ['name' => 'L\'Arc〜en〜Ciel', 'aliases' => ['ラルク', 'LArc en Ciel']],
    ['name' => 'X JAPAN', 'aliases' => ['X', 'エックス']],
    ['name' => 'LUNA SEA', 'aliases' => []],
    ['name' => 'THE YELLOW MONKEY', 'aliases' => ['イエモン']],
    ['name' => 'THEE MICHELLE GUN ELEPHANT', 'aliases' => ['ミッシェル']],
    ['name' => 'ELLEGARDEN', 'aliases' => ['エルレ']],
    ['name' => 'ASIAN KUNG-FU GENERATION', 'aliases' => ['アジカン']],
    ['name' => 'back number', 'aliases' => []],
    ['name' => 'Official髭男dism', 'aliases' => ['ヒゲダン']],
    ['name' => 'King Gnu', 'aliases' => ['キングヌー']],
    ['name' => 'マキシマム ザ ホルモン', 'aliases' => ['ホルモン']],
    ['name' => 'UVERworld', 'aliases' => []],
    ['name' => 'B\'z', 'aliases' => ['ビーズ']],
    ['name' => 'JUDY AND MARY', 'aliases' => ['JAM']],
    ['name' => 'THE ORAL CIGARETTES', 'aliases' => ['オーラル']],
    ['name' => 'BLUE ENCOUNT', 'aliases' => []],
    ['name' => '9mm Parabellum Bullet', 'aliases' => ['キューミリ']],
    ['name' => 'THE BACK HORN', 'aliases' => []],
    ['name' => 'Base Ball Bear', 'aliases' => ['ベボベ']],
    ['name' => 'KANA-BOON', 'aliases' => ['カナブーン']],
    ['name' => 'フジファブリック', 'aliases' => ['Fujifabric']],
    ['name' => 'くるり', 'aliases' => ['Quruli']],
    ['name' => 'ポルノグラフィティ', 'aliases' => ['Porno Graffitti']],
    ['name' => 'レミオロメン', 'aliases' => []],
    ['name' => 'チャットモンチー', 'aliases' => []],
    ['name' => 'シド', 'aliases' => ['SID']],
    ['name' => 'Acid Black Cherry', 'aliases' => ['ABC']],
    ['name' => 'Do As Infinity', 'aliases' => []],
    ['name' => 'Every Little Thing', 'aliases' => ['ELT']],
    ['name' => 'DREAMS COME TRUE', 'aliases' => ['ドリカム']],
    ['name' => 'いきものがかり', 'aliases' => ['Ikimonogakari']],
    ['name' => 'コブクロ', 'aliases' => ['Kobukuro']],
    ['name' => 'ゆず', 'aliases' => ['Yuzu']],
    ['name' => 'ORANGE RANGE', 'aliases' => ['オレンジレンジ']],
    ['name' => '175R', 'aliases' => ['イナゴライダー']],
    ['name' => 'ロードオブメジャー', 'aliases' => []],
    ['name' => '湘南乃風', 'aliases' => ['Shonan no Kaze']],
    ['name' => '氣志團', 'aliases' => ['Kishidan']],
    ['name' => 'ゴールデンボンバー', 'aliases' => ['金爆']],
    ['name' => 'SEKAI NO OWARI', 'aliases' => ['セカオワ']],
    ['name' => 'Mrs. GREEN APPLE', 'aliases' => ['ミセス']],
    ['name' => 'sumika', 'aliases' => []],
    ['name' => 'SUPER BEAVER', 'aliases' => []],
    ['name' => 'UNISON SQUARE GARDEN', 'aliases' => ['USG']],
    ['name' => '凛として時雨', 'aliases' => ['Ling tosite sigure']],
    ['name' => 'サカナクション', 'aliases' => ['Sakanaction']],
    ['name' => 'THE ALFEE', 'aliases' => []],
    ['name' => 'BOØWY', 'aliases' => ['ボウイ']],
    ['name' => 'TM NETWORK', 'aliases' => ['TMN']],
    ['name' => '安全地帯', 'aliases' => ['Anzenchitai']],
    ['name' => 'オフコース', 'aliases' => ['Off Course']],
    ['name' => 'TUBE', 'aliases' => []],
    ['name' => 'レベッカ', 'aliases' => ['REBECCA']],
    ['name' => 'プリンセス プリンセス', 'aliases' => ['プリプリ']],
    ['name' => 'チェッカーズ', 'aliases' => []],
    ['name' => 'ZARD', 'aliases' => []],
    ['name' => 'TRF', 'aliases' => []],
    ['name' => 'WANDS', 'aliases' => []],
    ['name' => 'FIELD OF VIEW', 'aliases' => []],
    ['name' => 'DEEN', 'aliases' => []],
    ['name' => 'T-BOLAN', 'aliases' => []],
    ['name' => 'SIAM SHADE', 'aliases' => []],
    ['name' => 'Janne Da Arc', 'aliases' => []],
    ['name' => 'L\'Arc〜en〜Ciel', 'aliases' => ['ラルク']],
    ['name' => 'GLAY', 'aliases' => []],
    ['name' => '黒夢', 'aliases' => []],
    ['name' => 'SADS', 'aliases' => []],
    ['name' => 'DIR EN GREY', 'aliases' => []],
    ['name' => 'the GazettE', 'aliases' => []],
    ['name' => 'シド', 'aliases' => []],
    ['name' => 'MUCC', 'aliases' => []],
    ['name' => 'Plastic Tree', 'aliases' => []],
    ['name' => 'Lynch.', 'aliases' => []],
    ['name' => '摩天楼オペラ', 'aliases' => []],
    ['name' => '陰陽座', 'aliases' => ['Onmyoza']],
    ['name' => 'BABYMETAL', 'aliases' => []],
    ['name' => 'Perfume', 'aliases' => ['パフューム']],
    ['name' => 'Capsule', 'aliases' => []],
    ['name' => '電気グルーヴ', 'aliases' => ['Denki Groove']],
    ['name' => 'サカナクション', 'aliases' => []],
    ['name' => 'フレデリック', 'aliases' => ['Frederic']],
    ['name' => 'クリープハイプ', 'aliases' => []],
    ['name' => 'マカロニえんぴつ', 'aliases' => []],
    ['name' => 'ヤバイTシャツ屋さん', 'aliases' => ['ヤバT']],
    ['name' => '04 Limited Sazabys', 'aliases' => ['フォーリミ']],
    ['name' => 'KICK THE CAN CREW', 'aliases' => []],
    ['name' => 'RIP SLYME', 'aliases' => []],
    ['name' => 'KREVA', 'aliases' => []],
    ['name' => 'Dragon Ash', 'aliases' => []],
    ['name' => 'm-flo', 'aliases' => []],
    ['name' => 'ORANGE RANGE', 'aliases' => []],
    ['name' => 'HOME MADE 家族', 'aliases' => []],
    ['name' => 'ケツメイシ', 'aliases' => []],
    ['name' => '湘南乃風', 'aliases' => []],
    ['name' => 'Def Tech', 'aliases' => []],
    ['name' => 'HY', 'aliases' => []],
    ['name' => 'BEGIN', 'aliases' => []],
    ['name' => 'MONGOL800', 'aliases' => ['モンパチ']],
    ['name' => 'ガガガSP', 'aliases' => []],
    ['name' => '銀杏BOYZ', 'aliases' => []],
    ['name' => 'くるり', 'aliases' => []],
    ['name' => 'サンボマスター', 'aliases' => []],
    ['name' => 'THE BLUE HEARTS', 'aliases' => ['ブルーハーツ']],
    ['name' => 'Hi-STANDARD', 'aliases' => ['ハイスタ']],
    ['name' => 'BRAHMAN', 'aliases' => []],
    ['name' => '10-FEET', 'aliases' => []],
    ['name' => 'MAN WITH A MISSION', 'aliases' => ['MWAM']],
    ['name' => 'Fear, and Loathing in Las Vegas', 'aliases' => ['FaLiLV']],
    ['name' => 'coldrain', 'aliases' => []],
    ['name' => 'Crossfaith', 'aliases' => []],
    ['name' => 'Crystal Lake', 'aliases' => []],
    ['name' => 'ROTTENGRAFFTY', 'aliases' => []],
    ['name' => 'SiM', 'aliases' => []],
    ['name' => 'HEY-SMITH', 'aliases' => []],
    ['name' => 'SHANK', 'aliases' => []],
    ['name' => 'dustbox', 'aliases' => []],
    ['name' => 'TOTALFAT', 'aliases' => []],
    ['name' => 'GOOD4NOTHING', 'aliases' => []],
    ['name' => 'locofrank', 'aliases' => []],
    ['name' => 'ELLEGARDEN', 'aliases' => []],
    ['name' => 'ストレイテナー', 'aliases' => ['STRAIGHTENER']],
    ['name' => 'Nothing\'s Carved In Stone', 'aliases' => ['NCIS']],
    ['name' => 'THE NOVEMBERS', 'aliases' => []],
    ['name' => 'People In The Box', 'aliases' => []],
    ['name' => 'plenty', 'aliases' => []],
    ['name' => 'ART-SCHOOL', 'aliases' => []],
    ['name' => 'GRAPEVINE', 'aliases' => []],
    ['name' => 'スガシカオ', 'aliases' => ['Shikao Suga']],
    ['name' => '秦基博', 'aliases' => ['Motohiro Hata']],
    ['name' => '山崎まさよし', 'aliases' => ['Masayoshi Yamazaki']],
    ['name' => '斉藤和義', 'aliases' => ['Kazuyoshi Saito']],
    ['name' => '奥田民生', 'aliases' => ['Tamio Okuda']],
    ['name' => '椎名林檎', 'aliases' => ['Ringo Sheena']],
    ['name' => '東京事変', 'aliases' => ['Tokyo Jihen']],
    ['name' => '米津玄師', 'aliases' => ['Kenshi Yonezu', 'ハチ']],
    ['name' => '藤井風', 'aliases' => ['Fujii Kaze']],
    ['name' => 'あいみょん', 'aliases' => ['Aimyon']],
    ['name' => '優里', 'aliases' => ['Yuuri']],
    ['name' => 'Vaundy', 'aliases' => []],
    ['name' => 'Ado', 'aliases' => []],
    ['name' => 'Eve', 'aliases' => []],
    ['name' => 'ずっと真夜中でいいのに。', 'aliases' => ['ZUTOMAYO']],
    ['name' => 'ヨルシカ', 'aliases' => ['Yorushika']],
    ['name' => '緑黄色社会', 'aliases' => ['Ryokuoushoku Shakai']],
    ['name' => 'Mrs. GREEN APPLE', 'aliases' => ['ミセス']],
    ['name' => 'King Gnu', 'aliases' => []],
    ['name' => 'Official髭男dism', 'aliases' => ['ヒゲダン']],

    ['name' => '宇多田ヒカル', 'aliases' => ['Hikaru Utada']],
    ['name' => 'aiko', 'aliases' => []],
    ['name' => '椎名林檎', 'aliases' => ['Ringo Sheena']],
    ['name' => '中島美嘉', 'aliases' => ['Mika Nakashima']],
    ['name' => '安室奈美恵', 'aliases' => ['Namie Amuro']],
    ['name' => '浜崎あゆみ', 'aliases' => ['Ayumi Hamasaki']],
    ['name' => 'MISIA', 'aliases' => []],
    ['name' => 'YUKI', 'aliases' => []],
    ['name' => 'Aimer', 'aliases' => []],
    ['name' => 'LiSA', 'aliases' => []],
    ['name' => '藍井エイル', 'aliases' => ['Eir Aoi']],
    ['name' => '大黒摩季', 'aliases' => []],
    ['name' => '広瀬香美', 'aliases' => ['Kohmi Hirose']],
    ['name' => '松任谷由実', 'aliases' => ['Yuming']],
    ['name' => '中島みゆき', 'aliases' => ['Miyuki Nakajima']],
    ['name' => 'JUJU', 'aliases' => []],
    ['name' => '絢香', 'aliases' => ['Ayaka']],
    ['name' => '家入レオ', 'aliases' => ['Leo Ieiri']],
    ['name' => '西野カナ', 'aliases' => ['Kana Nishino']],
    ['name' => '倖田來未', 'aliases' => ['Kumi Koda']],
    ['name' => '平原綾香', 'aliases' => ['Ayaka Hirahara']],
    ['name' => '手嶌葵', 'aliases' => ['Aoi Teshima']],
    ['name' => '松田聖子', 'aliases' => ['Seiko Matsuda']],
    ['name' => '中森明菜', 'aliases' => ['Akina Nakamori']],
    ['name' => '工藤静香', 'aliases' => ['Shizuka Kudo']],
    ['name' => '小泉今日子', 'aliases' => ['Kyoko Koizumi']],
    ['name' => '南野陽子', 'aliases' => ['Yoko Minamino']],
    ['name' => '渡辺美里', 'aliases' => ['Misato Watanabe']],
    ['name' => '華原朋美', 'aliases' => ['Tomomi Kahala']],
    ['name' => 'hitomi', 'aliases' => []],
    ['name' => 'Chara', 'aliases' => []],
    ['name' => 'UA', 'aliases' => []],
    ['name' => 'Cocco', 'aliases' => []],
    ['name' => 'YUI', 'aliases' => []],
    ['name' => 'miwa', 'aliases' => []],
    ['name' => '大塚愛', 'aliases' => ['Ai Otsuka']],
    ['name' => '木村カエラ', 'aliases' => ['Kaela Kimura']],
    ['name' => '安藤裕子', 'aliases' => ['Yuko Ando']],
    ['name' => '柴咲コウ', 'aliases' => ['Ko Shibasaki']],
    ['name' => '松たか子', 'aliases' => ['Takako Matsu']],
    ['name' => 'May J.', 'aliases' => []],
    ['name' => 'BENI', 'aliases' => []],
    ['name' => '青山テルマ', 'aliases' => ['Thelma Aoyama']],
    ['name' => '土岐麻子', 'aliases' => ['Asako Toki']],
    ['name' => 'EGO-WRAPPIN\'', 'aliases' => []],
    ['name' => 'UA', 'aliases' => []],
    ['name' => 'BONNIE PINK', 'aliases' => []],
    ['name' => '松浦亜弥', 'aliases' => ['Aya Matsuura']],
    ['name' => '高橋洋子', 'aliases' => ['Yoko Takahashi']],
    ['name' => '林原めぐみ', 'aliases' => ['Megumi Hayashibara']],
    ['name' => '坂本真綾', 'aliases' => ['Maaya Sakamoto']],
    ['name' => '水樹奈々', 'aliases' => ['Nana Mizuki']],
    ['name' => '田村ゆかり', 'aliases' => ['Yukari Tamura']],
    ['name' => '堀江由衣', 'aliases' => ['Yui Horie']],
    ['name' => '花澤香菜', 'aliases' => ['Kana Hanazawa']],
    ['name' => '内田真礼', 'aliases' => ['Maaya Uchida']],
    ['name' => '早見沙織', 'aliases' => ['Saori Hayami']],
    ['name' => '上坂すみれ', 'aliases' => ['Sumire Uesaka']],
    ['name' => '雨宮天', 'aliases' => ['Sora Amamiya']],
    ['name' => 'TrySail', 'aliases' => []],
    ['name' => 'ClariS', 'aliases' => []],
    ['name' => 'fripSide', 'aliases' => []],
    ['name' => 'Kalafina', 'aliases' => []],

    ['name' => '山下達郎', 'aliases' => ['Tatsuro Yamashita']],
    ['name' => '桑田佳祐', 'aliases' => ['Keisuke Kuwata']],
    ['name' => '福山雅治', 'aliases' => ['Masaharu Fukuyama']],
    ['name' => '平井堅', 'aliases' => ['Ken Hirai']],
    ['name' => '玉置浩二', 'aliases' => ['Koji Tamaki']],
    ['name' => '氷室京介', 'aliases' => ['Kyosuke Himuro']],
    ['name' => '布袋寅泰', 'aliases' => ['Tomoyasu Hotei']],
    ['name' => 'GACKT', 'aliases' => []],
    ['name' => '稲葉浩志', 'aliases' => ['Koshi Inaba']],
    ['name' => '桜井和寿', 'aliases' => ['Kazutoshi Sakurai']],
    ['name' => '藤井フミヤ', 'aliases' => ['Fumiya Fujii']],
    ['name' => '井上陽水', 'aliases' => ['Yosui Inoue']],
    ['name' => '吉田拓郎', 'aliases' => ['Takuro Yoshida']],
    ['name' => '長渕剛', 'aliases' => ['Tsuyoshi Nagabuchi']],
    ['name' => '小田和正', 'aliases' => ['Kazumasa Oda']],
    ['name' => '大瀧詠一', 'aliases' => ['Eiichi Ohtaki']],
    ['name' => '佐野元春', 'aliases' => ['Motoharu Sano']],
    ['name' => '尾崎豊', 'aliases' => ['Yutaka Ozaki']],
    ['name' => '尾崎紀世彦', 'aliases' => ['Kiyohiko Ozaki']],
    ['name' => '前川清', 'aliases' => ['Kiyoshi Maekawa']],
    ['name' => '郷ひろみ', 'aliases' => ['Hiromi Go']],
    ['name' => '西城秀樹', 'aliases' => ['Hideki Saijo']],
    ['name' => '野口五郎', 'aliases' => ['Goro Noguchi']],
    ['name' => '五木ひろし', 'aliases' => ['Hiroshi Itsuki']],
    ['name' => '氷川きよし', 'aliases' => ['Kiyoshi Hikawa']],
    ['name' => '細川たかし', 'aliases' => ['Takashi Hosokawa']],
    ['name' => '三山ひろし', 'aliases' => ['Hiroshi Miyama']],
    ['name' => '山川豊', 'aliases' => ['Yutaka Yamakawa']],
    ['name' => '北島三郎', 'aliases' => ['Saburo Kitajima']],
    ['name' => '美川憲一', 'aliases' => ['Kenichi Mikawa']],
    ['name' => '松山千春', 'aliases' => ['Chiharu Matsuyama']],
    ['name' => '谷村新司', 'aliases' => ['Shinji Tanimura']],
    ['name' => 'さだまさし', 'aliases' => ['Masashi Sada']],
    ['name' => '徳永英明', 'aliases' => ['Hideaki Tokunaga']],
    ['name' => '久保田利伸', 'aliases' => ['Toshinobu Kubota']],
    ['name' => '清水翔太', 'aliases' => ['Shota Shimizu']],
    ['name' => '三浦大知', 'aliases' => ['Daichi Miura']],
    ['name' => '星野源', 'aliases' => ['Gen Hoshino']],
    ['name' => '米津玄師', 'aliases' => ['Kenshi Yonezu', 'ハチ']],
    ['name' => '藤井風', 'aliases' => ['Fujii Kaze']],
    ['name' => '優里', 'aliases' => ['Yuuri']],
    ['name' => 'Vaundy', 'aliases' => []],
    ['name' => 'Eve', 'aliases' => []],
    ['name' => 'yama', 'aliases' => []],
    ['name' => '菅田将暉', 'aliases' => ['Masaki Suda']],
    ['name' => '香取慎吾', 'aliases' => []],
    ['name' => '草彅剛', 'aliases' => []],
    ['name' => '木村拓哉', 'aliases' => []],
    ['name' => '堂本剛', 'aliases' => []],
    ['name' => '堂本光一', 'aliases' => []],

    ['name' => '嵐', 'aliases' => ['ARASHI']],
    ['name' => 'SMAP', 'aliases' => []],
    ['name' => 'TOKIO', 'aliases' => []],
    ['name' => 'KinKi Kids', 'aliases' => []],
    ['name' => 'V6', 'aliases' => []],
    ['name' => 'King & Prince', 'aliases' => ['キンプリ']],
    ['name' => 'Snow Man', 'aliases' => []],
    ['name' => 'SixTONES', 'aliases' => []],
    ['name' => 'KAT-TUN', 'aliases' => []],
    ['name' => 'NEWS', 'aliases' => []],
    ['name' => '関ジャニ∞', 'aliases' => ['Kanjani Eight']],
    ['name' => 'Hey! Say! JUMP', 'aliases' => []],
    ['name' => 'Sexy Zone', 'aliases' => []],
    ['name' => 'ジャニーズWEST', 'aliases' => ['WEST.']],
    ['name' => '乃木坂46', 'aliases' => []],
    ['name' => '櫻坂46', 'aliases' => ['欅坂46']],
    ['name' => '日向坂46', 'aliases' => []],
    ['name' => 'AKB48', 'aliases' => []],
    ['name' => 'SKE48', 'aliases' => []],
    ['name' => 'NMB48', 'aliases' => []],
    ['name' => 'HKT48', 'aliases' => []],
    ['name' => 'STU48', 'aliases' => []],
    ['name' => 'ももいろクローバーZ', 'aliases' => ['ももクロ']],
    ['name' => 'Perfume', 'aliases' => []],
    ['name' => 'BABYMETAL', 'aliases' => []],
    ['name' => 'BiSH', 'aliases' => []],
    ['name' => 'BiS', 'aliases' => []],
    ['name' => 'でんぱ組.inc', 'aliases' => []],
    ['name' => '私立恵比寿中学', 'aliases' => ['エビ中']],
    ['name' => 'SUPER☆GiRLS', 'aliases' => []],
    ['name' => 'フェアリーズ', 'aliases' => []],
    ['name' => '東京女子流', 'aliases' => []],

    ['name' => 'ハチ', 'aliases' => ['米津玄師', 'Kenshi Yonezu']],
    ['name' => 'DECO*27', 'aliases' => []],
    ['name' => 'wowaka', 'aliases' => []],
    ['name' => 'じん', 'aliases' => ['自然の敵P']],
    ['name' => 'カンザキイオリ', 'aliases' => []],
    ['name' => 'ピノキオピー', 'aliases' => []],
    ['name' => 'ナユタン星人', 'aliases' => []],
    ['name' => 'kz', 'aliases' => ['livetune']],
    ['name' => 'ryo', 'aliases' => ['supercell']],
    ['name' => 'Orangestar', 'aliases' => []],
    ['name' => 'みきとP', 'aliases' => []],
    ['name' => '40mP', 'aliases' => []],
    ['name' => '八王子P', 'aliases' => []],
    ['name' => 'れるりり', 'aliases' => []],
    ['name' => 'syudou', 'aliases' => []],
    ['name' => 'Kanaria', 'aliases' => []],
    ['name' => 'Ayase', 'aliases' => ['YOASOBI']],

    ['name' => 'JAM Project', 'aliases' => []],
    ['name' => 'FLOW', 'aliases' => []],
    ['name' => 'EGOIST', 'aliases' => []],
    ['name' => 'supercell', 'aliases' => []],
    ['name' => 'ClariS', 'aliases' => []],
    ['name' => 'fripSide', 'aliases' => []],
    ['name' => 'Kalafina', 'aliases' => []],
    ['name' => '梶浦由記', 'aliases' => ['Yuki Kajiura']],
    ['name' => '藍井エイル', 'aliases' => []],
    ['name' => 'LiSA', 'aliases' => []],
    ['name' => 'Aimer', 'aliases' => []],
    ['name' => 'TrySail', 'aliases' => []],
    ['name' => '水樹奈々', 'aliases' => []],
    ['name' => '坂本真綾', 'aliases' => []],
    ['name' => '林原めぐみ', 'aliases' => []],
    ['name' => '高橋洋子', 'aliases' => []],

    ['name' => '美空ひばり', 'aliases' => ['Hibari Misora']],
    ['name' => '石川さゆり', 'aliases' => []],
    ['name' => '坂本冬美', 'aliases' => []],
    ['name' => '北島三郎', 'aliases' => []],
    ['name' => '五木ひろし', 'aliases' => []],
    ['name' => '氷川きよし', 'aliases' => []],
    ['name' => '細川たかし', 'aliases' => []],
    ['name' => '天童よしみ', 'aliases' => []],
    ['name' => '八代亜紀', 'aliases' => []],
    ['name' => '森進一', 'aliases' => []],
    ['name' => '森昌子', 'aliases' => []],
    ['name' => '千昌夫', 'aliases' => []],
    ['name' => '島倉千代子', 'aliases' => []],
    ['name' => '都はるみ', 'aliases' => []],

    ['name' => '中田ヤスタカ', 'aliases' => ['Yasutaka Nakata']],
    ['name' => 'tofubeats', 'aliases' => []],
    ['name' => 'banvox', 'aliases' => []],
    ['name' => 'SEKAI NO OWARI', 'aliases' => ['End of the World']],

    // 80年代〜90年代歌謡曲・ポップス
    ['name' => '渡辺美里', 'aliases' => ['Misato Watanabe']],
    ['name' => '岡村靖幸', 'aliases' => ['Yasuyuki Okamura']],
    ['name' => 'TM NETWORK', 'aliases' => ['TMN']],
    ['name' => '大江千里', 'aliases' => ['Senri Oe']],
    ['name' => '久保田利伸', 'aliases' => ['Toshinobu Kubota']],
    ['name' => '米米CLUB', 'aliases' => ['Kome Kome Club']],
    ['name' => 'プリンセス プリンセス', 'aliases' => ['プリプリ']],
    ['name' => 'レベッカ', 'aliases' => ['REBECCA']],
    ['name' => 'チェッカーズ', 'aliases' => []],
    ['name' => '安全地帯', 'aliases' => ['Anzenchitai']],
    ['name' => '中村あゆみ', 'aliases' => ['Ayumi Nakamura']],
    ['name' => 'ZIGGY', 'aliases' => []],

    // 90年代ロック・バンドブーム
    ['name' => 'JUDY AND MARY', 'aliases' => ['JAM']],
    ['name' => 'THE YELLOW MONKEY', 'aliases' => ['イエモン']],
    ['name' => 'LUNA SEA', 'aliases' => []],
    ['name' => '黒夢', 'aliases' => []],
    ['name' => 'SADS', 'aliases' => []],
    ['name' => 'SIAM SHADE', 'aliases' => []],
    ['name' => 'WANDS', 'aliases' => []],
    ['name' => 'DEEN', 'aliases' => []],
    ['name' => 'FIELD OF VIEW', 'aliases' => []],
    ['name' => 'T-BOLAN', 'aliases' => []],
    ['name' => 'BAAD', 'aliases' => []],
    ['name' => 'ZYYG', 'aliases' => []],
    ['name' => 'PENICILLIN', 'aliases' => []],
    ['name' => 'Janne Da Arc', 'aliases' => []],

    // 小室ファミリー（あなたの世代のど真ん中）
    ['name' => 'globe', 'aliases' => []],
    ['name' => 'TRF', 'aliases' => []],
    ['name' => '安室奈美恵', 'aliases' => ['Namie Amuro']],
    ['name' => '華原朋美', 'aliases' => ['Tomomi Kahala']],
    ['name' => '篠原涼子', 'aliases' => ['Ryoko Shinohara']],
    ['name' => 'hitomi', 'aliases' => []],

    // 90年代J-POP黄金期
    ['name' => 'スピッツ', 'aliases' => ['Spitz']],
    ['name' => 'Mr.Children', 'aliases' => ['ミスチル']],
    ['name' => 'B\'z', 'aliases' => ['ビーズ']],
    ['name' => 'GLAY', 'aliases' => []],
    ['name' => 'L\'Arc〜en〜Ciel', 'aliases' => ['ラルク']],
    ['name' => 'THE BOOM', 'aliases' => []],
    ['name' => 'DREAMS COME TRUE', 'aliases' => ['ドリカム']],
    ['name' => '槇原敬之', 'aliases' => ['Noriyuki Makihara']],
    ['name' => '小沢健二', 'aliases' => ['Ozawa Kenji']],
    ['name' => 'スチャダラパー', 'aliases' => []],

    // 00年代初期（青春J-POP）
    ['name' => 'スキマスイッチ', 'aliases' => []],
    ['name' => 'コブクロ', 'aliases' => []],
    ['name' => 'いきものがかり', 'aliases' => []],
    ['name' => 'ORANGE RANGE', 'aliases' => []],
    ['name' => 'HY', 'aliases' => []],
    ['name' => 'BUMP OF CHICKEN', 'aliases' => ['バンプ']],
    ['name' => 'ELLEGARDEN', 'aliases' => ['エルレ']],
    ['name' => 'ASIAN KUNG-FU GENERATION', 'aliases' => ['アジカン']],
    ['name' => 'レミオロメン', 'aliases' => []],
    ['name' => 'ロードオブメジャー', 'aliases' => []],

    // 80年代アイドル（世代的に刺さる）
    ['name' => '松田聖子', 'aliases' => ['Seiko Matsuda']],
    ['name' => '中森明菜', 'aliases' => ['Akina Nakamori']],
    ['name' => '小泉今日子', 'aliases' => ['Kyoko Koizumi']],
    ['name' => '南野陽子', 'aliases' => ['Yoko Minamino']],
    ['name' => '浅香唯', 'aliases' => ['Yui Asaka']],
    ['name' => '荻野目洋子', 'aliases' => ['Yoko Oginome']],
    ['name' => '工藤静香', 'aliases' => ['Shizuka Kudo']],
    ['name' => 'Wink', 'aliases' => []],

    // 80〜90年代男性アイドル
    ['name' => '光GENJI', 'aliases' => []],
    ['name' => '男闘呼組', 'aliases' => []],
    ['name' => 'チェッカーズ', 'aliases' => []],
    ['name' => '田原俊彦', 'aliases' => ['Toshihiko Tahara']],
    ['name' => '近藤真彦', 'aliases' => ['Masahiko Kondo']],
    ['name' => '少年隊', 'aliases' => []],

    // 80〜90年代アニメ・特撮
    ['name' => '影山ヒロノブ', 'aliases' => []],
    ['name' => '串田アキラ', 'aliases' => []],
    ['name' => '水木一郎', 'aliases' => ['Ichiro Mizuki']],
    ['name' => '堀江美都子', 'aliases' => []],
    ['name' => 'MoJo', 'aliases' => []],

    ['name' => 'BUMP OF CHICKEN', 'aliases' => ['バンプ']],
    ['name' => 'RADWIMPS', 'aliases' => ['ラッド']],
    ['name' => 'ELLEGARDEN', 'aliases' => ['エルレ']],
    ['name' => 'ASIAN KUNG-FU GENERATION', 'aliases' => ['アジカン']],
    ['name' => '9mm Parabellum Bullet', 'aliases' => ['キューミリ']],
    ['name' => 'the pillows', 'aliases' => []],
    ['name' => '凛として時雨', 'aliases' => ['Ling tosite sigure']],
    ['name' => 'UNISON SQUARE GARDEN', 'aliases' => ['USG']],
    ['name' => 'KANA-BOON', 'aliases' => ['カナブーン']],
    ['name' => 'フジファブリック', 'aliases' => []],
    ['name' => 'Base Ball Bear', 'aliases' => ['ベボベ']],
    ['name' => 'チャットモンチー', 'aliases' => []],
    ['name' => 'レミオロメン', 'aliases' => []],
    ['name' => 'マキシマム ザ ホルモン', 'aliases' => ['ホルモン']],
    ['name' => 'UVERworld', 'aliases' => []],
    ['name' => 'ONE OK ROCK', 'aliases' => ['ワンオク']],
    ['name' => 'SPYAIR', 'aliases' => []],
    ['name' => 'BLUE ENCOUNT', 'aliases' => []],
    ['name' => '04 Limited Sazabys', 'aliases' => ['フォーリミ']],
    ['name' => 'ヤバイTシャツ屋さん', 'aliases' => ['ヤバT']],

    ['name' => 'YUI', 'aliases' => []],
    ['name' => 'miwa', 'aliases' => []],
    ['name' => '大塚愛', 'aliases' => ['Ai Otsuka']],
    ['name' => '木村カエラ', 'aliases' => ['Kaela Kimura']],
    ['name' => '絢香', 'aliases' => ['Ayaka']],
    ['name' => '西野カナ', 'aliases' => ['Kana Nishino']],
    ['name' => '家入レオ', 'aliases' => ['Leo Ieiri']],
    ['name' => 'スキマスイッチ', 'aliases' => []],
    ['name' => 'コブクロ', 'aliases' => []],
    ['name' => 'いきものがかり', 'aliases' => []],
    ['name' => '平井堅', 'aliases' => ['Ken Hirai']],
    ['name' => '清水翔太', 'aliases' => ['Shota Shimizu']],

    ['name' => '松山千春', 'aliases' => ['Chiharu Matsuyama']],
    ['name' => '谷村新司', 'aliases' => ['Shinji Tanimura']],
    ['name' => 'さだまさし', 'aliases' => ['Masashi Sada']],
    ['name' => 'オフコース', 'aliases' => ['Off Course']],
    ['name' => 'アリス', 'aliases' => []],
    ['name' => 'かぐや姫', 'aliases' => []],
    ['name' => '井上陽水', 'aliases' => ['Yosui Inoue']],
    ['name' => '吉田拓郎', 'aliases' => ['Takuro Yoshida']],
    ['name' => '中島みゆき', 'aliases' => ['Miyuki Nakajima']],
    ['name' => '松任谷由実', 'aliases' => ['Yuming']],
    ['name' => '山下達郎', 'aliases' => ['Tatsuro Yamashita']],
    ['name' => '大滝詠一', 'aliases' => ['Eiichi Ohtaki']],
    ['name' => '佐野元春', 'aliases' => ['Motoharu Sano']],
    ['name' => '浜田省吾', 'aliases' => ['Shogo Hamada']],
    ['name' => '尾崎豊', 'aliases' => ['Yutaka Ozaki']],

    ['name' => 'BOØWY', 'aliases' => ['ボウイ']],
    ['name' => 'THE BLUE HEARTS', 'aliases' => ['ブルーハーツ']],
    ['name' => 'RCサクセション', 'aliases' => ['RC']],
    ['name' => 'ARB', 'aliases' => []],
    ['name' => 'レベッカ', 'aliases' => []],
    ['name' => 'プリンセス プリンセス', 'aliases' => ['プリプリ']],
    ['name' => 'PERSONZ', 'aliases' => []],
    ['name' => 'ZIGGY', 'aliases' => []],

    ['name' => '松田聖子', 'aliases' => ['Seiko Matsuda']],
    ['name' => '中森明菜', 'aliases' => ['Akina Nakamori']],
    ['name' => '小泉今日子', 'aliases' => ['Kyoko Koizumi']],
    ['name' => '南野陽子', 'aliases' => ['Yoko Minamino']],
    ['name' => '浅香唯', 'aliases' => ['Yui Asaka']],
    ['name' => '荻野目洋子', 'aliases' => ['Yoko Oginome']],
    ['name' => 'Wink', 'aliases' => []],
    ['name' => '田原俊彦', 'aliases' => ['Toshihiko Tahara']],
    ['name' => '近藤真彦', 'aliases' => ['Masahiko Kondo']],
    ['name' => '少年隊', 'aliases' => []],
    ['name' => '光GENJI', 'aliases' => []],


];
