name: Deploy to Coreserver

on:
  push:
    branches:
      - main
      - master
      - redesign

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./*"
        target: ${{ secrets.DEPLOY_PATH }}
